name: 'cargo test & clippy'
on: 
  push:
    paths:
    - "**/Cargo.lock"
    - "**/Cargo.toml"
    - "**/*.rs"
  pull_request:
    paths:
    - "**/Cargo.lock"
    - "**/Cargo.toml"
    - "**/*.rs"

# Make sure CI fails on all warnings, including Clippy lints
# env:
#  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_test_check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update &&\
          sudo apt-get install libusb-1.0-0-dev -y
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Cargo test
        run: cargo test -- --nocapture

